// <auto-generated />
using System;
using DamiFYP.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DamiFYP.Persistence.Migrations
{
    [DbContext(typeof(DamiContext))]
    [Migration("20260719115043_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DamiFYP.Domain.Models.BloodType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BloodTypeName")
                        .HasColumnType("integer");

                    b.Property<long>("DamiUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("DamiUserId")
                        .IsUnique();

                    b.ToTable("BloodTypes");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.Conversation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("MatchId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.ConversationParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ConversationId")
                        .HasColumnType("bigint");

                    b.Property<long>("DamiUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("DamiUserId");

                    b.ToTable("ConversationParticipants");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DamiUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("KeyCloakId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastActiveAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("DamiUser", (string)null);
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DonationPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("BloodTypeName")
                        .HasColumnType("integer");

                    b.Property<long>("DamiUserId")
                        .HasColumnType("bigint");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DamiUserId");

                    b.ToTable("DonationPosts");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DonationRequest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BloodTypeName")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<long>("DamiUserId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("NeededByDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Urgency")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DamiUserId");

                    b.ToTable("DonationRequest", (string)null);
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.Match", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<double?>("DistanceKm")
                        .HasColumnType("double precision");

                    b.Property<long>("DonationPostId")
                        .HasColumnType("bigint");

                    b.Property<long>("DonationRequestId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonationPostId");

                    b.HasIndex("DonationRequestId");

                    b.ToTable("Match", (string)null);
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("ConversationParticipantId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ConversationParticipantId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.BloodType", b =>
                {
                    b.HasOne("DamiFYP.Domain.Models.DamiUser", "DamiUser")
                        .WithOne("BloodType")
                        .HasForeignKey("DamiFYP.Domain.Models.BloodType", "DamiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamiUser");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.Conversation", b =>
                {
                    b.HasOne("DamiFYP.Domain.Models.Match", "Match")
                        .WithOne("Conversation")
                        .HasForeignKey("DamiFYP.Domain.Models.Conversation", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.ConversationParticipant", b =>
                {
                    b.HasOne("DamiFYP.Domain.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DamiFYP.Domain.Models.DamiUser", "DamiUser")
                        .WithMany("ConversationParticipants")
                        .HasForeignKey("DamiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("DamiUser");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DonationPost", b =>
                {
                    b.HasOne("DamiFYP.Domain.Models.DamiUser", "DamiUser")
                        .WithMany("DonationPosts")
                        .HasForeignKey("DamiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamiUser");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DonationRequest", b =>
                {
                    b.HasOne("DamiFYP.Domain.Models.DamiUser", "DamiUser")
                        .WithMany("DonationRequests")
                        .HasForeignKey("DamiUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamiUser");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.Match", b =>
                {
                    b.HasOne("DamiFYP.Domain.Models.DonationPost", "DonationPost")
                        .WithMany("Matches")
                        .HasForeignKey("DonationPostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DamiFYP.Domain.Models.DonationRequest", "DonationRequest")
                        .WithMany("Matches")
                        .HasForeignKey("DonationRequestId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DonationPost");

                    b.Navigation("DonationRequest");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.Message", b =>
                {
                    b.HasOne("DamiFYP.Domain.Models.ConversationParticipant", "ConversationParticipant")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationParticipantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ConversationParticipant");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.ConversationParticipant", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DamiUser", b =>
                {
                    b.Navigation("BloodType")
                        .IsRequired();

                    b.Navigation("ConversationParticipants");

                    b.Navigation("DonationPosts");

                    b.Navigation("DonationRequests");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DonationPost", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.DonationRequest", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("DamiFYP.Domain.Models.Match", b =>
                {
                    b.Navigation("Conversation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
